### ISSUE TITLE
Audio Service Non-Functioning

### ISSUE THREAD

**Issue by generallynonsensical** [OpenVoiceOS/ovos-audio#20]
`System:
  Host: ***** Kernel: 5.19.0-46-generic x86_64 bits: 64 compiler: N/A
    Desktop: KDE Plasma 5.24.7 tk: Qt 5.15.3 wm: kwin_x11 vt: 1 dm: SDDM
    Distro: Ubuntu 22.04.2 LTS (Jammy Jellyfish)`

`Machine:
  Type: Laptop System: Apple product: MacBookPro8,2 v: 1.0
    serial: <superuser required> Chassis: type: 10 v: Mac-94245A3940C91C80
    serial: <superuser required>
  Mobo: Apple model: Mac-94245A3940C91C80 v: MacBookPro8,2
    serial: <superuser required> UEFI: Apple v: MBP81.88Z.0050.B00.1804101331
    date: 04/10/18`

`CPU:
  Info: quad core model: Intel Core i7-2635QM bits: 64 type: MT MCP
    smt: enabled arch: Sandy Bridge rev: 7 cache: L1: 256 KiB L2: 1024 KiB
    L3: 6 MiB`

`Audio:
  Device-1: Intel 6 Series/C200 Series Family High Definition Audio
    driver: snd_hda_intel v: kernel bus-ID: 00:1b.0 chip-ID: 8086:1c20
    class-ID: 0403
  Device-2: AMD Caicos HDMI Audio [Radeon HD 6450 / 7450/8450/8490 OEM R5
    230/235/235X OEM]
    driver: snd_hda_intel v: kernel pcie: speed: 5 GT/s lanes: 8
    bus-ID: 01:00.1 chip-ID: 1002:aa98 class-ID: 0403
  Sound Server-1: ALSA v: k5.19.0-46-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes`

**_ After running via terminal, the last four lines of output are: _**

`2023-07-16 08:50:49.738 - audio - ovos_plugin_manager.audio:load_audio_service_plugins:84 - INFO - Loading audio service plugin: ovos_audio_simple`

`2023-07-16 08:50:49.738 - audio - ovos_audio.audio:load_services:75 - INFO - OCP - OVOS Common Play set as default backend`

`2023-07-16 08:50:49.741 - audio - ovos_audio.service:on_alive:27 - INFO - Audio service is alive.`

`2023-07-16 08:50:49.845 - audio - ovos_audio.service:on_error:35 - ERROR - Audio service failed to launch (No TTS loaded).`

The audio service stays running but will not output audio.

I have removed and installed audio software several times. I have install version `0.0.2a14`

**Comment by JarbasAl** [comment]
ERROR - Audio service failed to launch (No TTS loaded).  <- your TTS plugin is either invalid or not installed?

**Comment by generallynonsensical** [comment]
TTS plugin installed, but both mimic and mimic3 were installed. Removed mimic and the accompanying server and it seems to be working. No error on audio startup.
