### ISSUE TITLE
ovos-audio stops speaking when some chars are present

### ISSUE THREAD

**Issue by nmaupu** [OpenVoiceOS/ovos-audio#33]
Hey ! Weird bug here !

Config: rpi4 8GB with raspbian OVOS

When trying to process TTS with `ovos-audio`, if an _upper case letter_ is in the string spoken, ovos-audio stops speaking until a restart of the service occurs.

Logs continue to show requests but nothing happens on speakers.

```
ovos-speak "i am a test" --> works
ovos-speak "i am a test" --> works
ovos-speak "i aM a test" --> doesn't work
ovos-speak "i am a test" --> doesn't work
...
```
Same behavior happens when asking something returning an upper case letter in the string:

`ovos-say-to "what time is it ?"`
  - response "five fifty six" --> ok
  - response "It is five fifty six" --> not ok

EDIT:

I tried with a piper server on my local network. I can see that when `ovos audio` stops working, it logs sentences but the server is not called anymore.

**Comment by nmaupu** [comment]
No problem on server side to process this kind of requests:

```
curl "http://localhost:9666/synthesize/je%20suis%20un%20test" | aplay -i
curl "http://localhost:9666/synthesize/je%20suis%20un%20TEEESTE" | aplay -i
curl "http://localhost:9666/synthesize/je%20suis%20un%20TESTE" | aplay -i
```

All work without any issue.

**Comment by nmaupu** [comment]
After more testings:
`ovos-speak "it is not working ?"` works as expected whereas `ovos-speak "it is not working."` doesn't.

It seems that some characters trigger the problem and others don't.
- `?`, `,`, `:`,`(`,`)`,`|` --> ok
- `.`, `upper case`, `digits` --> makes ovos-audio stop working

**Comment by goldyfruit** [comment]
This is related to the TTS not to `ovos-audio` directly, which TTS plugin are you using?

**Comment by builderjer** [comment]
I think this is solved by adding `"sentence_tokenize": true` to the piper-tts plugin config?

**Comment by goldyfruit** [comment]
This has been fixed by this commit: https://github.com/OpenVoiceOS/ovos-tts-plugin-piper/commit/bd1c525325fadb4afb8e0dfde0b0c3940552c9b7

`sentence_tokenize` is for long sentence split.
