### ISSUE TITLE
The start/end_listening sounds should be called with the pulse media.role=phone to enable ducking

### ISSUE THREAD

**Issue by Ramblurr** [OpenVoiceOS/ovos-audio#36]
Copied from https://github.com/MycroftAI/mycroft-core/issues/3148

This will likely never get fixed upstream since MycrodtAI has moved on to dinkum. But now that I am building my home setup around ovos, maybe there is a chance?

The linked ticket describes the issue.

Basically, the start listening sound play command  should be passed the same environment as the tts play command.

This let's pulse properly handle ducking of the start listening sound.

Without this, as it currently stands, the start listening sound is played without the phone role, so it is treated as music. This is problematic because I want the start listening sound and the tts to be played at the same volume.

**Comment by emphasize** [comment]
Have to check `os.environ`. The way this is coded is weird and indicates the common `PULSE_PROP` environmental variable is `media.role=phone`

```python
_ENVIRONMENT = deepcopy(os.environ)
_ENVIRONMENT['PULSE_PROP'] = 'media.role=music'


def _get_pulse_environment(config):
    """Return environment for pulse audio depeding on ducking config."""
    tts_config = config.get('tts', {})
    if tts_config and tts_config.get('pulse_duck'):
        return _ENVIRONMENT
    else:
        return os.environ
```
