### ISSUE TITLE
Add some TTS to the requirements.txt?

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-audio#4]
It could be nice to add the default TTS to the `requirements.txt`, in my example I'm using Mimic2 as default TTS and Mimic as fallback which is pretty standard.

```json
  "tts": {
    "pulse_duck": true,
    "module": "ovos-tts-plugin-mimic2",
    "fallback_module": "ovos-tts-plugin-mimic"
  }
```

I would understand if you prefer stay neutral from a `requirements.txt` perspective.

**Comment by goldyfruit** [comment]
This `tts` sample comes from the default configuration file in `.../lib/python3.11/site-packages/ovos_config/mycroft.conf`

**Comment by JarbasAl** [comment]
we changed that to mimic3-server plugin in latest core, mimic2 will likely go down soon and the model is not public so it is impossible to self host 

i'm ok with adding a list of optional requirements.txt to this repo with recommended plugins, Docker should also include a few of them to allow users to easily switch

**Comment by goldyfruit** [comment]
I'm good to close this one, as `ovos-tts-mimic3-server` is already part of the requirements.

For Docker, `tts.list` support has been added by https://github.com/OpenVoiceOS/ovos-docker/commit/95e255bf10d297a50d5ad79c0e8a120b9173a53d
